$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
# Embed textures so direct file launches do not depend on cross-origin file images.
$textureNames = @('brain-material', 'stomach-material', 'bone-material', 'mouth-material', 'foot-sprite', 'foot-sprite-green')
$textureData = [ordered]@{}
foreach ($name in $textureNames) {
    $relativePath = "assets/$name.png"
    $textureData[$relativePath] = 'data:image/png;base64,' + [Convert]::ToBase64String([IO.File]::ReadAllBytes((Join-Path $projectRoot $relativePath)))
}
$assetScript = '/* Generated by tools/package-itch.ps1; do not edit. */' + "`nconst GAME_TEXTURES = " + (ConvertTo-Json -InputObject $textureData -Compress) + ';'
[IO.File]::WriteAllText((Join-Path $projectRoot 'assets/texture-data.js'), $assetScript, [Text.UTF8Encoding]::new($false))
$files = @(
    'index.html', 'startup.js', 'style.css', 'game.js', 'art-data.js', 'art-polish.js', 'scene-3d.js',
    'vendor/three.js', 'vendor/THREE-LICENSE.txt', 'assets/foot-shape.js',
    'assets/texture-data.js'
)
foreach ($relativePath in $files) {
    if (!(Test-Path -LiteralPath (Join-Path $projectRoot $relativePath) -PathType Leaf)) {
        throw "Missing game file: $relativePath"
    }
}
$outputDirectory = Join-Path $projectRoot 'dist'
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
$archivePath = Join-Path $outputDirectory 'glow-autopsy-pinball-itch.zip'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
$stream = [System.IO.File]::Open($archivePath, [System.IO.FileMode]::Create)
$archive = [System.IO.Compression.ZipArchive]::new($stream, [System.IO.Compression.ZipArchiveMode]::Create)
try {
    foreach ($relativePath in $files) {
        [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
            $archive, (Join-Path $projectRoot $relativePath), $relativePath,
            [System.IO.Compression.CompressionLevel]::Optimal
        ) | Out-Null
    }
} finally {
    $archive.Dispose()
    $stream.Dispose()
}
Write-Output "Created $archivePath ($($files.Count) files; index.html at archive root)."
